CREATE DATABASE IF NOT EXISTS jokes_db;
USE jokes_db;

CREATE TABLE IF NOT EXISTS saved_jokes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  joke TEXT NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);